language: python
sudo: false
install: travis_scripts/install.sh
cache:
    directories:
        - $HOME/.cache/pip
env:
  - JYTHON=true
  - TOXENV=py26
  - TOXENV=pep8
  - TOXENV=pylint
  - TOXENV=py27
  - TOXENV=py27_cython
  - TOXENV=py33
  - TOXENV=py33_cython
  - TOXENV=py34
  - TOXENV=py34_cython
  - TOXENV=pypy
  - TOXENV=pypy3
  - TOXENV=py27_smoke
  - TOXENV=py27_smoke_cython

script: travis_scripts/run_tests.sh
notifications:
  irc:
    channels:
      - "chat.freenode.net#falconframework"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true

before_install:
  - pip install codecov
after_success:
  - codecov
