language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - pypy
install:
  - pip install -r tests/requirements.txt --use-mirrors
  - python setup.py install
script: nosetests
notifications:
  email:
    - kurt.griffiths@rackspace.com
