language: python
install: pip install tox coveralls --use-mirrors
env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py27_cython
  - TOX_ENV=py33
  - TOX_ENV=py33_cython
  - TOX_ENV=py34
  - TOX_ENV=py34_cython
  - TOX_ENV=pypy
  - TOX_ENV=pep8
  - TOX_ENV=pylint
  - TOX_ENV=py27_smoke
  - TOX_ENV=py27_smoke_cython

script: tox -e $TOX_ENV
after_success: coveralls
notifications:
  email:
    - kurt.griffiths@rackspace.com
  irc:
    - "chat.freenode.net#falconframework"
